import { Inter, Roboto_Mono } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "../provider/AuthProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "FashionTex-HRD",
//   description: "Generated by Fashion Tex",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning data-theme="light">
      <head>
        <title>Fashion Tex</title>
        <link rel="shortcut icon" href="/favicon.ico" type="image/png" />
      </head>
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
